version: '3.8'
services:

  nginx:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      keycloak:
        condition: service_healthy
    networks:
      - proxy_network

  keycloak:
    image: jboss/keycloak
    environment:
      - KEYCLOAK_USER=${KEYCLOAK_USER}
      - KEYCLOAK_PASSWORD=${KEYCLOAK_PASSWORD}
      - DB_VENDOR=${KEYCLOAK_DB_VENDOR}
      - DB_ADDR=${KEYCLOAK_DB_ADDR}
      - DB_PORT=${KEYCLOAK_DB_PORT}
      - DB_DATABASE=${KEYCLOAK_DB_DATABASE}
      - DB_USER=${KEYCLOAK_DB_USER}
      - DB_PASSWORD=${KEYCLOAK_DB_PASSWORD}
    depends_on:
      - postgres
    networks:
      - proxy_network
      - keycloak_network
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://localhost:8080/auth/realms/master"]
      interval: 30s
      timeout: 10s
      retries: 3

  postgres:
    image: postgres
    environment:
      - POSTGRES_DB=${KEYCLOAK_DB_DATABASE}
      - POSTGRES_USER=${KEYCLOAK_DB_USER}
      - POSTGRES_PASSWORD=${KEYCLOAK_DB_PASSWORD}
    networks:
      - keycloak_network

networks:
  keycloak_network:
  proxy_network: